;;;; Copyright 2009 Josh Marchan
;;;;
;;;; This file is part of sykobot.
;;;;
;;;; For licensing and warranty information refer to COPYING
;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(in-package :sykobot)

(defcommand slap ("(\\S+)" nick)
  "Syntax: 'slap <nick>' - Slaps nick with something."
  (build-string "slaps " nick " with"
   random-elt '(" a man page"
		"a rather large squid"
		"a hydraulic pump"
		"a book by Stephen King"
		"a 10mbit network card"
		"a ladies handbag"
		"some girl scouts"
		"a football team"
		"a bottle"
		"a yellow marshmellow"
		"a match"
		"the queen of England"
		"a taxi"
		"100 feet of wire"
		"a bag of Cheerios"
		"a hat"
		"a fist"
		"the back hand"
		"with the forehead"
		"a computer moniter"
		"a coconut"
		"a microfone"
		"a cellphone"
		"a snowplough"
		"a doggy"
		"Bill Clinton"
		"a stone"
		"a club. With a nail in it"
		"a small asteroid rich in iron",
		"a small interstellar spaceship"
		"a fresh zuccini"
		"a laptop"
		"a big dictionary"
		"a baseball bat"
		"NeverNet"
		"some porn"
		"a mIRC script"
		"a canoe"
		"a tortoise"
		"a horse"
		"the book of Kells"
		"a whale"
		"a rubber dildo"
		"a well groomed poodle"
		"a channel operator"
		"a news paper (New York Times Sunday Edition)"
		"a gnarly werewolf"
		"a vampire. They really suck"
		"a perl script"
		"a bag of doggie chow"
		"a fat walrus"
		"an IP adress"
		"a catholic priest"
		"James Dean"
		"Ronald MacDonald (he *IS* good for something)"
		"a PRIVMSG"
		"an email adress"
		"some ANSI color codes"
		"a thermonuclear weapon. Yehaw"
		"the hitch hikers guide to the galaxy revised edition",
		"Nessie the Loch Ness monster",
		"a tuna. Still in the can! *BONK* That will leave a mark"
		"a few fluffy pillows"
		"a red chinese dragon"
		"a linux-manual (signed by L. Torvalds)"
		"Stage1"
		"Bill Gates underpants"
		"GM Abraham and the whole OW-Staff"
		"Sphere 1.0"
		"a Linuxkernel"
		"Lenin's Collected Works"
		"Stalin's Collected Works"
		"a iron Tux"
		"a glowing 23"
		"your mum (CLEAN YOUR ROOM!)"
		"a complete GNOME-Documentation"
		"a Portagetree"
		"thand[Z]'s transparent Tanga"
		"a Kernelpanic"
		"Windows Vista"
		"Windoze XP"
		"an AK-47 (die you imperialist dog!)",
		"a bag full with Michael Jacksons droped noses"
		"an NBP-Manifesto (Hail Limonew! Hail our Leader! Hail!)"
		"an NBP-Flag (Lead us to freedom Leader Limonew!)",
		"Mein Kampf (Doppelausgabe Hardcover)",
		"Invader Zim's iron fist"
		"some ASCII-Arts"
		"The Family Learning Channel"
		"GOD"
		"Dorian Grey's picture"
		"some unlocked Grenades *BOOM*"
		"the Win2k Buglist"
		"Debian SSH bug"
		"The whole Gnome enviromnet "
		"a widescreen TV (it can damage your brain!)"
		"a chain saw"
		"a huge tree"
		"a 50'' CRT monitor"
		"a warehouse (Quadratisch. Praktisch. Gut.)"
                " your mom"))))	       

